### ISSUE TITLE
stomp does not support content of nativeHeaders

### ISSUE THREAD

**Issue by DerekHQ** [emqx/emqx-stomp#52]
我发送的包为：
SEND
simpOrigDestination:/user/5733f858162de9253c0c3d38-583f84db26b4be1a0425f297/queue/store
destination:/topic/unresolved-user-destination
content-type:application/json;charset=UTF-8
content-length:24

{
  "content" : "ab"
}

但是我接收回来的包为：
MESSAGE
subscription:0
message-id:0
destination:/topic/unresolved-user-destination
content-type:text/plain
content-length:24

{
  "content" : "ab"
}

===============
即通过emqx broker relay 消息后，自定义的nativeHeaders内容没了；造成无法正确路由消息
开发环境是spring-messaging + websocket + stomp

注：切换apache-apollo服务，is work!

用apollo服务 接收回来的数据包为：
MESSAGE
subscription:0
ack:18
message-id:mq-1e22
simpOrigDestination:/user/5733f858162de9253c0c3d38-583f84db26b4be1a0425f297/queue/store
destination:/topic/unresolved-user-destination
content-type:application/json;charset=UTF-8
content-length:24

{
  "content" : "ab"
}

**Comment by tigercl** [comment]
@DerekHQ Sorry for later response. The error has been fixed in latest version.
